import './global.css';

export const metadata = {
  title: 'Welcome to stable-web',
  description: 'Generated by create-nx-workspace custom configurations enhance by Adnan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
